// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: cart_crud.sql

package repository

import (
	"context"
)

const createCart = `-- name: CreateCart :exec
INSERT INTO "cart" (
    "customer_id", "product_id"
) VALUES (
    $1, $2
)
`

type CreateCartParams struct {
	CustomerID int64
	ProductID  int64
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) error {
	_, err := q.db.ExecContext(ctx, createCart, arg.CustomerID, arg.ProductID)
	return err
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM "cart"
WHERE "id" = $1 AND "customer_id" = $2
`

type DeleteCartParams struct {
	ID         int64
	CustomerID int64
}

func (q *Queries) DeleteCart(ctx context.Context, arg DeleteCartParams) error {
	_, err := q.db.ExecContext(ctx, deleteCart, arg.ID, arg.CustomerID)
	return err
}
